version: "3.8"

services:
  main-app:
      build:
        context: ./main-app
        dockerfile: Dockerfile
      ports:
        - "3005:3005"
      depends_on:
        - product-service
        - cart-service
        - review-service
      environment:
        - HOSTNAME=main-app
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=product-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=product-db
    depends_on:
      - product-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=product-db", "--user=root", "--password=root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 60s

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=cart-db
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=cartdb
      - APP_ENV=docker
    depends_on:
      - cart-db
    healthcheck:
      test: ["CMD", "pg_isready", "--host=cart-db", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    command: bash -c "php artisan migrate && php -S 0.0.0.0:3002 -t public"
  
  review-service:
    build:
      context: ./review-service 
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=Dev@root23
      - MONGO_HOST=review-db
    depends_on:
      - review-db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  product-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product-db
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=127.0.0.1", "--user=root", "--password=root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 30s

  cart-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: cartdb
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  
  review-db:
    image: mongo:6.0
    container_name: review-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Dev@root23
    volumes:
      - review-db-data:/data/db

volumes:
  product-db-data:
  cart-db-data:
  review-db-data: 
